services:
  db:
    image: postgres:16
    env_file: .env 
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    env_file: .env 
    build:
      context: ./services/api-service
      dockerfile: Dockerfile.dev   
    command: npm run dev
    volumes:
      - ./services/api-service:/app
      - /app/node_modules
    depends_on:
      - db


  migrations-service:
    build:
      context: ./services/migrations-service
    env_file: .env 
    depends_on:
      - db

  
  redirect:
    build:
      context: ./services/redirect-service
      dockerfile: Dockerfile.dev   
    command: npm run dev
    env_file: .env
    ports: ["8081:8081"]
    depends_on:
      - api
    volumes:
      - ./services/redirect-service:/app
      - /app/node_modules
volumes:
  pgdata:
