services:
  db:
    image: postgres:16
    env_file: .env 
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    env_file: .env 
    build:
      context: .
      dockerfile: ./services/api-service/Dockerfile.dev   
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - api_node_modules:/app/node_modules
      - logs_volume:/app/logs
    depends_on:
      - db


  migrations-service:
    build:
      context: ./services/migrations-service
    env_file: .env 
    depends_on:
      - db

  
  redirect:
    build:
      context: ./services/redirect-service
      dockerfile: Dockerfile.dev   
    command: npm run dev
    env_file: .env
    ports: ["8081:8081"]
    depends_on:
      - api
    volumes:
      - ./services/redirect-service:/app
      - /app/node_modules
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
volumes:
  pgdata:
  api_node_modules:
  logs_volume:
